spring:
  profiles:
    active: dev
  config:
    override-none: true
    override-system-properties: false

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-config-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7001:7002/eureka/,http://127.0.0.1:7001:7003/eureka/
  instance:
    prefer-ip-address: true

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-config-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7001:7002/eureka/,http://127.0.0.1:7001:7003/eureka/
  instance:
    prefer-ip-address: true